### ISSUE TITLE
remove outdated filesystem recommendation

### ISSUE THREAD

**Issue by rptaylor** [multixscale/cvmfs-tutorial-hpc-best-practices#53]
https://github.com/cvmfs/doc-cvmfs/pull/224

**Comment by vvolkl** [comment]
Referring to [this passage](https://github.com/multixscale/cvmfs-tutorial-hpc-best-practices/blob/main/docs/configuration_hpc.md?plain=1#L55):
```
The loopback filesystem files can be created using `dd` or `mkfs`. They should be formatted as an `ext3`, `ext4`,
or `xfs` file system, and should be 15% larger than the cache size configured on the nodes (with `CVMFS_QUOTA_LIMIT`).
```

**Comment by rptaylor** [comment]
Particularly here:  https://github.com/multixscale/cvmfs-tutorial-hpc-best-practices/blob/e2136ec45fca1afe2b7be5d855d48a60ac93a937/docs/access/stratum1.md?plain=1#L48
