### ISSUE TITLE
contents for section "Performance aspects of CernVM-FS"

### ISSUE THREAD

**Issue by boegel** [multixscale/cvmfs-tutorial-hpc-best-practices#8]

**Comment by boegel** [comment]
To assess startup performance, we can look into a single-binary as a base case (HPL?), a typical scientific app (OpenFOAM), and a large Python app (TensorFlow).

For OS jitter, OpenFOAM is a good use case, since it's known to be quite sensitive to OS jitter (if just one core is temporarily busy with something else than running OpenFOAM, the whole multi-node run will be significantly slower).

**Comment by HereThereBeDragons** [comment]
if you dont have a benchmark setup yet, i would have some python scripts.. but they need a bit of cleanup first.
eventually we want to use them in some form to have a continous performance testing.
but let me know if you'd prefer using those or use your own solution

**Comment by HereThereBeDragons** [comment]
i opened up a PR with a cleaned up version of the performance benchmark i used for chep: [cvmfs/cvmfs#3372](https://github.com/cvmfs/cvmfs/pull/3372) 
while for sure **it will still change**, e.g. accepting command line arguments, it is already now fully functional. if you already want to run know some benchmarking tests. 
all you need to modify are the user params in `start_benchmark.py` and `start_visualization.py` (and read the comments there)
all code expects to be run from `cvmfs/test/performance-benchmark`
workflow:
1) `python3 start_benchmark.py` --write to--> `./data/<maybe_some_subdir>/*.csv`
2) `./data/<maybe_some_subdir>` --takes--> `python3 start_visualization.py`  --writes-to--> `./results/<maybe some subdir>/*.pdf`
(you can set the `outdir` to something else if you want)

**Comment by boegel** [comment]
I have puzzled together some stats on startup performance of:

* Python (`python -V`): https://github.com/boegel/cvmfs-tutorial-hpc-best-practices/blob/perf/cvmfs_perf_python_hpcugent.ipynb
* TensorFlow (`python -c 'import tensorflow'`): https://github.com/boegel/cvmfs-tutorial-hpc-best-practices/blob/perf/cvmfs_perf_tensorflow_hpcugent.ipynb

Still work-in-progress, because not all tests were done with the same Python/TensorFlow versions, but the results look pretty good, seems like they will definitely support the narrative we have in mind for this section.
